### PR TITLE
fix(hoverProvider): get typescript type

### PR DESCRIPTION
**Pull request by Simon-He95**

### CODE REVIEW

**Comment by Simon-He95** [comment]
@DominicVonk Hi, Is this plugin still being maintained, maybe I can help make it better

**Comment by DominicVonk** [comment]
@Simon-He95 This is currently built in https://code.visualstudio.com/docs/typescript/typescript-editing#_inlay-hints

**Comment by Simon-He95** [comment]
> @Simon-He95 This is currently built in [code.visualstudio.com/docs/typescript/typescript-editing#_inlay-hints](https://code.visualstudio.com/docs/typescript/typescript-editing#_inlay-hints)

I know, but The built-in performance of vscode is not as good as this one offers

**Comment by Simon-He95** [comment]
I like Parameter-Hints performance more

Parameter-Hints
image

vscode:
image

**Comment by Simon-He95** [comment]
@DominicVonk， What's more, the vscode does not provide the function of hover to display parameter details. Before the vscode support, I think this extension will be a better choice

**Comment by Simon-He95** [comment]
This pr is closed, I plan to continue to maintain it on my fork version

**Comment by DominicVonk** [comment]
@Simon-He95 maybe we can implement this here? https://github.com/DominicVonk/inlay-hints

**Pull request closed without merging**
